### ISSUE TITLE
Install Help:  ros2 run joy joy_node: Package 'joy' not found

### ISSUE THREAD

**Issue by teknetik** [Ar-Ray-code/ps_ros2_common#8]
While I understand this problem is outside your library I was hoping you might be kind enough to offer some advice?

`ubuntu@ubuntu:~/ros2_ws$ sudo apt install -y ros-foxy-joy*

Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'ros-foxy-joy' for glob 'ros-foxy-joy*'
Note, selecting 'ros-foxy-joy-dbgsym' for glob 'ros-foxy-joy*'
Note, selecting 'ros-foxy-joy-linux-dbgsym' for glob 'ros-foxy-joy*'
Note, selecting 'ros-foxy-joy-teleop' for glob 'ros-foxy-joy*'
Note, selecting 'ros-foxy-joy-linux' for glob 'ros-foxy-joy*'
ros-foxy-joy is already the newest version (3.0.0-2focal.20211112.214147).
ros-foxy-joy-dbgsym is already the newest version (3.0.0-2focal.20211112.214147).
ros-foxy-joy-linux is already the newest version (3.0.0-2focal.20211112.213818).
ros-foxy-joy-linux-dbgsym is already the newest version (3.0.0-2focal.20211112.213818).
ros-foxy-joy-teleop is already the newest version (1.2.1-1focal.20211112.201933).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

rosdep update

    reading in sources list data from /etc/ros/rosdep/sources.list.d
    Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/osx-homebrew.yaml

Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/base.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/python.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/ruby.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/releases/fuerte.yaml
Query rosdistro index https://raw.githubusercontent.com/ros/rosdistro/master/index-v4.yaml
Skip end-of-life distro "ardent"
Skip end-of-life distro "bouncy"
Skip end-of-life distro "crystal"
Skip end-of-life distro "dashing"
Skip end-of-life distro "eloquent"
Add distro "foxy"
Add distro "galactic"
Skip end-of-life distro "groovy"
Skip end-of-life distro "hydro"
Skip end-of-life distro "indigo"
Skip end-of-life distro "jade"
Skip end-of-life distro "kinetic"
Skip end-of-life distro "lunar"
Add distro "melodic"
Add distro "noetic"
Add distro "rolling"
updated cache in /home/ubuntu/.ros/rosdep/sources.cache

rosdep install -a
    #All required rosdeps installed successfully

source ~/ros2_foxy/ros2-linux/setup.bash

ros2 run joy joy_node
    Package 'joy' not found`

**Comment by Ar-Ray-code** [comment]
Did you run `source /opt/ros/foxy/setup.bash` before running `ros2 run ...` ?

**Comment by Ar-Ray-code** [comment]
Added command.

https://github.com/Ar-Ray-code/ps_ros2_common/commit/72a95321d59262a4d1c361d74874112692416d08#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

**Comment by teknetik** [comment]
Now my terrible stupidity is posted on the internet FOREVER! :D

That seems to be exactly it

`source /opt/ros/foxy/setup.bash

source ~/ros2_foxy/ros2-linux/setup.bash
source ~/ros2_ws/install/setup.bash`

I guess I am confused as to which one I need to run when but will create a shell script I can call to source them all to avoid this. Thanks so much for your advice and for building this lib. Very excited to get controller support for my WIP robot :)
